### ISSUE TITLE
Проверка окончания игры

### ISSUE THREAD

**Issue by stden** [levelp/Qt_FifteenPuzzle#12]
Если пользователь правильно сложил головоломку, нужно показывать соответствующую надпись.

**Comment by BogdanovPD** [comment]
Добрый день, Денис.

Удалите меня пожалуйста из группы levelp. Я не занимаюсь у вас в группе уже
полгода, но сообщения по-прежнему постоянно приходят.

Спасибо.

24 Авг 2016 г. 22:23 пользователь "Denis Stepulenok" <
notifications@github.com> написал:

**Comment by stden** [comment]
a511bcb02e7593c287485834d4af268611786a9f
